name: tf dynamic module cicd

on:
  push:
    branches: [dev , master]

jobs:

  Initialise:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Init
      run: terraform init
    - name: Validate
      run: terraform validate 
    - name: Plan
      run: terraform plan -auto-approve
#     - name: Apply
#       run: terraform apply -var-file="demo.tfvars"
