name: tf dynamic module cicd

on: workflow_dispatch

jobs:

  manual-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: verify
      run: terraform init
    - name: deploy
      run: terraform apply -auto-approve
