name: tf dynamic module cicd

on: workflow_dispatch

jobs:

  Initialise:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Init
      run: terraform init
    - name: Apply
      run: terraform apply -auto-approve
